/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BookResponse {
  archived?: boolean;
  authorName?: string;
  cover?: Array<string>;
  id?: number;

  owner?: string;
  rate?: number;
  shareable?: boolean;
  synopsis?: string;
  title?: string;
  categoryName?: string;
  categoryId?: number;
  location?: string;
  latitude?: number;
  longitude?: number;
  fullAddress?: string;
  video?: string;
  videoUrl?: string;
}
